#!/usr/bin/env bash

set -o errexit
declare bin="$HOME/bin"

# Create directory for user-local executables
setup() {
    [ -d "$bin" ] || mkdir "$bin"
    echo $'PATH=$PATH:'"$bin" >> "$HOME/.bashrc"
}

install() {
    local name=$1
    local url=$2
    echo -n "Installing $name ..."
    curl --silent -L "$url" > "$bin/$name"
    chmod +x "$bin/$name"
    echo
}

main() {

    # Only run in SAP Business Application Studio
    # shellcheck disable=2154
    if ! grep -i sap <<< "$externalEntrypoint" >/dev/null; then
      echo Only for use in SAP Business Application Studio
      exit 1
    fi

    setup
    install yq https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
    install jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    npm install --global url-decode-encode-cli
    echo "Please now restart the terminal (Ctrl-D then Ctrl-\`) to have the new shell settings take effect ..."
}

main "$@"
