#!/usr/bin/env bash

set -o errexit

source ./settings.sh   # configuration
source ./localutils.sh # getservicekey getval gettoken
source ./management.sh # management API functions

main() {

  local output=silent # or verbose
  local command=$1
  local functions
  functions=$(management_functions)

  # Either we're being asked to list the functions (for bash completion)
  # or a function is being invoked.
  case $command in
    completion | "")
      echo "$functions"
      ;;
    *)
      if [[ ! "$functions" =~ $command ]]; then
        err Command \""$command"\" is not recognised
        exit 1
      fi
      shift

      # Retrieve service key and parse out relevant sections
      sk=$(getservicekey "$instance" "$servicekey")
      management=$(getval "$sk" "(.credentials//.).management[0]")

      # Determine API call details for MANAGEMENT incl OAuth 2.0 token
      uri=$(getval "$management" .uri)
      oauth=$(getval "$management" .oa2)
      token=$(gettoken "$oauth")

      # Now we can run the requested command
      $command "$@"
      ;;
  esac

}

main "$@"
