#!/usr/bin/env bash

set -o errexit

qos=0

output=silent # silent or verbose

source ./settings.sh   # configuration
source ./localutils.sh # getservicekey getval gettoken
source ./messaging.sh  # messaging API functions

main() {

  local qos=0
  local command=$1
  local functions
  functions=$(messaging_functions)

  # Either we're being asked to list the functions (for bash completion)
  # or a function is being invoked.
  case $command in
    completion | "")
      echo "$functions"
      ;;
    *)
      # TODO make this check more accurate
      if [[ ! "$functions" =~ $command ]]; then
        err Command \""$command"\" is not recognised
        exit 1
      fi
      shift

      # Retrieve service key and parse out relevant sections.
      sk=$(getservicekey "$instance" "$servicekey")
      messaging=$(getval "$sk" "(.credentials//.).messaging")
      httprest=$(getval "$messaging" '.[] | select(.broker.type == "saprestmgw")')

      # Determine API call details for MESSAGING-HTTPREST incl OAuth 2.0 token
      uri=$(getval "$httprest" .uri)
      oauth=$(getval "$httprest" .oa2)
      token=$(gettoken "$oauth")

      # Now we can run the requested command
      $command "$@"
      ;;
  esac

}

main "$@"
