#!/usr/bin/env bash

# Get messaging dashboard URL from the service info and open it. This is
# what we did in Part 2 of the series, specifically here:
# https://www.youtube.com/watch?v=Ct-uiu3RRZs&list=PL6RpkC85SLQCf--P9o7DtfjEcucimapUf&index=3&t=1990s

source ./settings.sh

function open_command() {
    if [[ -z "$WSL_DISTRO_NAME" ]]; then
        open "$1"
    else
        cmd.exe /C start "$1"
    fi
}

# Get the details of the service instance, pull out the dashboard URL
dashboard_url=$(cf service "${instance}" \
                   | awk '/^dashboard:/ { print $2 }')

# Call open_command function with dashboard URL to open it
open_command $dashboard_url