#!/usr/bin/env bash

set -o errexit

# Set up messaging service instance and service key
# Sort of idempotent - can rerun if required.

source ./settings

parameters=$(yq r -j - <<EO_PARAMETERS
emname: "${instance}"
options:
  management: true
  messagingrest: true
EO_PARAMETERS
)

# Login in if required - check by issuing 'cf target' and
# and then issuing 'cf login' if the return code was high
cf target >/dev/null 2>&1 || cf login

# Create instance of messaging service
cf create-service "${service}" "${plan}" "${instance}" -c "${parameters}"

# Create service key
cf create-service-key "${instance}" "${servicekey}"
