#!/usr/bin/env bash

declare fontname="Victor Mono"
declare fontsize="16"
declare bg="transparent"
declare fg="ivory"

dot \
  -Tpng \
  -Nfontname="$fontname" \
  -Nfontsize="$fontsize" \
  -Nfontcolor="$fg" \
  -Ncolor="$fg" \
  -Ecolor="$fg" \
  -Gfontname="$fontname" \
  -Gfontcolor="$fg" \
  -Gcolor="$fg" \
  -Gbgcolor="$bg"


