#!/usr/bin/env bash

set -o errexit

declare queues
queues=$(cd .. && cache ./management list_queues)

for queue in $(jq -r '.[] .name' <<< "$queues" | sort); do
  echo "$queue"
  (cd .. && cache ./management list_queue_subscriptions "$queue") \
    | jq -r '.[] | .queueName + " " + .topicPattern'

done

